- .travis.yml
Recent builds have failed due to a bug in Maven. Setting `JAVA_HOME` is a temporary fix.
> Travis-CI: Work around issue with Maven

- java/src/main/java/gherkin/GherkinDialectProvider.java
- java/src/main/java/gherkin/TokenMatcher.java
- java/src/test/java/gherkin/ParserTest.java
Tracked down two different NullPointerExceptions when parsing a feature
* One when the language was missing
* One when the table for a Scenario Outline was missing
I committed them in two commits so they should be easier to cherry pick.
I am not certain about the solution for the missing table in the Scenario Outline. The only option I could find, except the one I used, was to wrap the logic in Parser.matchTokenAt_20 with a try catch, catch NullPointerException and repackage the NPE as a ParserException.UnexpectedEOFException. It got ugly.
Instead I went through the methods called in TokenMatcher and made sure token.line wasn't called without checking for eof on the token. That solution felt better compared to wrap a lot of logic and assume that the NPE caught was due to an unexpected …
> Unit tests for java parser

- go/Makefile
by telling make that it needs them for doing their acceptance tests
This now exercises the acceptance tests again by simply typing `make` after changing a Go file.
@muhqu Please take a look
> Rebuild generators on change

- ruby/lib/gherkin3/gherkin_line.rb
- testdata/good/scenario_outline_no_newline.feature
- testdata/good/scenario_outline_no_newline.feature.ast.json
- testdata/good/scenario_outline_no_newline.feature.pickles.json
- testdata/good/scenario_outline_no_newline.feature.tokens
If there is not blank or newline after the last cell of the last row in the example table, then the last parsed table row will have one cell to little, when using the ruby version of Gherkin3. This in turn causes a inconsistent cell count exception.
Several of the feature files for Cucumber contain this type of example tables from using the following constructs in the feature files:
```
Given a file named "features/f.feature" with:
"""
<snip>
Examples:
| Value           |
| Also Irrelevant |
"""
```
> Ruby: One cell to little when no newline after example table

- dotnet/Gherkin/TokenMatcher.cs
- go/matcher.go
- java/src/main/java/gherkin/TokenMatcher.java
- javascript/lib/gherkin/token_matcher.js
- ruby/lib/gherkin3/token_matcher.rb
- testdata/good/docstrings.feature
- testdata/good/docstrings.feature.ast.json
- testdata/good/docstrings.feature.pickles.json
- testdata/good/docstrings.feature.tokens
See https://github.com/cucumber/cucumber-ruby/issues/863#issuecomment-119888052 and https://github.com/cucumber/cucumber-ruby-core/pull/93
I've added what I think is the right failing test, but I'm still hunting around for the right way to implement the solution. Any tips?
> Escaped DocString content

- python/gherkin-python.razor
- python/gherkin3/ast_builder.py
- python/gherkin3/ast_node.py
- python/gherkin3/dialect.py
- python/gherkin3/gherkin_line.py
- python/gherkin3/token.py
- python/gherkin3/token_matcher.py
- python/gherkin3/token_scanner.py
(See cucumber/gherkin-python#1 for details.)
----
**NOTE: Untested!**
I tried to run `make` after committing my changes, but I got an error:
```
$ make 
cd dotnet && make
rm -f .sln_built_debug
mono --version
make[1]: mono: No such file or directory
make[1]: *** [.sln_built_debug] Error 1
make: *** [dotnet/.compared] Error 2
```
I’m afraid I don’t know anything about dotnet… :-(
In the meantime, I’ll be waiting for Travis to do its wonderful work.
> (Python) Use new-style classes

- python/gherkin3/dialect.py
- python/gherkin3/token_scanner.py
Also:
* Factor out `DIALECT_FILE_PATH` from `DIALECTS`
* Move `DIALECTS` from a class variable to a module variable
AFTER making these changes, I discovered a nearly line-for-line mirror of them in the Ruby implementation.  Knowing this, I named the `DIALECT_FILE_PATH` variable after its Ruby implementation equivalent (originally the variable was named something else).
So…happy accident. :-)
> (Python) Close file descriptors

- CHANGELOG.md
I moved the issue links after the summaries, because it:
- …**puts the summary first,** which is the primary thing of interest to the reader; and, it
- …**makes it easier for humans that edit the file,** because you can put each link on a line below the change, which makes it much easier to read as plain text (in keeping with the spirit of Markdown)
> Fix #75: Use “Keep A CHANGELOG” format

- dotnet/Gherkin/TokenScanner.cs
- go/gherkin3.go
- java/src/main/java/gherkin/TokenScanner.java
- javascript/lib/gherkin/token_scanner.js
- python/gherkin3/token_scanner.py
- ruby/lib/gherkin3/token_scanner.rb
* The description is taken from the README.md
* I looked up the basic rules for “documentation comments” for each language, in order to provide (minimal but functional) support for documentation generators
> Add short description comments for TokenScanner

- python/gherkin3/dialect.py
- python/gherkin3/token_matcher.py
Slightly more “pythonic” code. :)
> (Python) Use `@properties` in Dialect class

- ruby/gherkin-ruby.razor
- ruby/lib/gherkin3/parser.rb
- ruby/lib/gherkin3/token_scanner.rb
- ruby/spec/gherkin3/parser_spec.rb
This one is based on #99. #99 should be merge before this one is merged. With this PR you can pass `Parser#parse` a feature file as string.
> Fix problem with strings

- python/gherkin3/token_matcher.py
Here is a separate PR for this change.
> (Python) Don’t use mutable default arguments

- python/setup.py
These are used by https://caniusepython3.com/project/gherkin3 and other PyPI-related tools.
> Python package: add trove classifiers

- README.md
The characters used for the left and right arrows are not outside the
range of standard and extended ASCII characters and the font used by
Windows-based browsers doesn't render them at the same width as the rest
of the characters, so the box sides and corners do not line up.
I replaced the left and right arrow characters with the '<' and '>
characters so the boxes look right when viewed from a browser under
Windows. I also replaced the down arrow with a 'V', even though the down
arrow is the same width, so all the arrows look consistent.
> ASCII art doesn't render properly on Windows

- dotnet/Gherkin/TokenMatcher.cs
- go/matcher.go
- java/src/main/java/gherkin/TokenMatcher.java
- javascript/lib/gherkin/token_matcher.js
- objective-c/Gherkin/GHTokenMatcher.m
- python/gherkin3/token_matcher.py
- ruby/lib/gherkin3/token_matcher.rb
- testdata/good/descriptions.feature
- testdata/good/descriptions.feature.ast.json
- testdata/good/descriptions.feature.pickles.json
- testdata/good/descriptions.feature.tokens
Now the unescaping of docstring separators is performed unconditionally when matching the token "other". Since the token "other" is used both for descriptions and docstrings, also in descriptions `\"\"\"` is replaced with `"""` (why anyone would write `\"\"\"` in a description is another question).
This PR changes the behaviour so that only in docstrings  `\"\"\"` is replaced with `"""`.
> Do not change escaped docstring separators in descriptions.

- .travis.yml
- objective-c/.travis.yml
- python/Makefile
Build (including the acceptance tests) the objective-c version on the top Travis build. Compile the objective-c version on the gherkin-objective-c Travis build.
Set the language explicitly on all jobs in the Travis matrix, otherwise the default version of the language is used instead of the specified one. That means that in theory we have tested on 4 different Ruby version and 2 different Python version, but in practice we have only tested on Ruby 1.9.3 and Python 2.7.3 (see https://travis-ci.org/cucumber/gherkin3/jobs/84295786#L1108 and https://travis-ci.org/cucumber/gherkin3/jobs/89541942#L1107)
Use jruby 1.7.22 instead of jruby-head, the jruby-head version issues warnings that interfere with the error tests (see https://travis-ci.org/cucumber/gherkin3/jobs/89730239#L430).
Run the unit …
> Build objective-c on Travis. Fix Travis language settings.

- python/gherkin3/token_scanner.py
By monkey-patching `io.StringIO` to be `cStringIO.StringIO`, `token_scanner.py` was inadvertently breaking breaking any code that expected `io.StringIO` to be of type `type`, because `cStringIO.StringIO` has type `builtin_function_or_method`.
Practically speaking, this means that any code that attempted to interact with `io.StringIO` as one would interact with a class (e.g. subclassing, accessing a class attribute, etc) would fail with an error, for example:
* Subclassing: `TypeError: Error when calling the metaclass bases`
* Attribute access: `AttributeError: 'builtin_function_or_method' object has no attribute 'write'`
The [Celery](https://github.com/celery/celery/) project does exactly this in the `celery.five` [module](https://github.com/celery/celery/blob/v3.1.16/celery/five.py#L383-L …
> Prevent token_scanner.py from (recklessly) monkey-patching io.StringIO.

- README.md
- dotnet/README.md
- go/README.md
- java/README.md
- javascript/README.md
- objective-c/README.md
- python/README.md
- ruby/README.md
SVG badges look much better on hi-res displays.
> Make all badges SVG

- dotnet/Gherkin/gherkin-languages.json
Gnéchlár is a more correct word for a software feature in irish.
> Add gnéchlár for feature for irish

- ruby/lib/gherkin/ast_builder.rb
- ruby/spec/gherkin/parser_spec.rb
Updated some of the :type keys that were Strings instead of Symbols so
that they are all now Symbols. This will fix issue #155.
> More consistent AST node types.

- go/ast.go
- go/astbuilder.go
- go/astjson.go
Remove the extra ast class ExamplesBase and let a custom Json marshalling handle that the TableRow attribute of Examples shall be included in the Json output if it is an empty list, but it should not be included in the Json output if it has the value nil.
For a background, see the discussion starting here: https://github.com/cucumber/gherkin-go/commit/85ee76ba2fb6064c12f075d7733d21e7227a4c2d#commitcomment-16445193.
> Refactor "allow incomplete scenario outlines" for go.

- ruby/gherkin-ruby.razor
- ruby/lib/gherkin/ast_builder.rb
- ruby/lib/gherkin/parser.rb
- ruby/lib/gherkin/pickles/compiler.rb
- ruby/lib/gherkin/token_matcher.rb
- ruby/lib/gherkin/token_scanner.rb
The **gherkin** ruby gem use at various place `require_relative` to require other files from the gem.
As it happens that these files can be (and in fact are also) required by `require` elsewhere (for example directly in **cucumber-core**), this causes a discrepancy leading to these files being loaded twice.
Indeed, my ruby setup using rbenv on OS X relies on the fact that the main exposed directory for ruby is `/usr/local/opt/rbenv/versions/2.3.0/lib/ruby` which is a symbolic link for `/usr/local/Cellar/rbenv/1.0.0/versions/2.3.0/lib` (standard Homebrew + rbenv setup).
So `require 'gherkin/token_matcher'` ends up loading `/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gherkin-3.2.0/lib/gherkin/token_matcher.rb` (once, even if required several times, due to the fact that …
> Ruby: Use require instead of require_relative

- CONTRIBUTING.md
In the Adding or updating an i18n language section the `gherkin-languages.json` file is referenced. There was a typo in the file which this commit corrects.
> Correct typo of gherkin-languages.json file

- CONTRIBUTING.md
As mentioned in [issue 183](https://github.com/cucumber/gherkin/issues/183) `go` was not listed as a prerequisite for the build. This commit adds `go` to the list of prerequisites.
> Add go as a build prerequisite

- perl/lib/Gherkin/Exceptions.pm
In the previous implementation, structured error data was being
discarded at instantiation due to instant stringification in the
constructor; I believe this is how the Python implementation still
works. Changed the behaviour to maintain actual Exception objects
that know how to be stringified by default. This will allow
consumers the ability to catch and recover based on more than the
string itself, as well as giving consumers the ability to write
more comprehensive error messages should they wish to.
This also makes `Gherkin::Exceptions::SingleParser` an abstract class in practice, as it no longer has a constructor.
Braver developers than I might choose to investigate changing the other language implementations to work in a similar matter, but my opinion is that this isn't different …
> Stop the Perl exceptions from being prematurely stringified

- CONTRIBUTING.md
A slip of the keyboard transformed "from" to "form" in
`CONTRIBUTING.md`. This commit corrects that mistake.
> from was spelled form

- CHANGELOG.md
Corrected the links to the pull request and committer that did not
line up with the change to which they referred. Looks like it might
have been a copy/pasted from another change.
> Fixed attribution error.

- javascript/index.js
@aslakhellesoy 
for cucumber-js to work in the browser we browserify the code. The fact that window is checked for before module.exports breaks the browserified code.
> javascript: check for module before window

- CONTRIBUTING.md
Updating the language count from 6 to 8.
> Update contributing.md for the new language count

- .travis.yml
- perl/dist.ini
https://travis-ci.org/cucumber/gherkin/jobs/138044300 failed because a dep required a newer version of Perl. 5.14 is now 5 years old, happy to bounce the minimum version up.
> Bump minimum Perl version to 5.14

- java/src/main/java/gherkin/GherkinDialectProvider.java
The class **GherkinDialectProvider** fails to load the **gherkin-languages.json** on **Android**. To fix that, the path should start with '**/**' and therefore contain the full path to the file.
> Using full path when loading gherkin-languages.json

- java/pom.xml
With https://github.com/cucumber/gherkin2/pull/166 and https://github.com/cucumber/cucumber-jvm/pull/873 support to execute Cucumber-JVM in OSGi containers was added. To not lose that ability when upgrading Cucumber-JVM to use Gherkin v4, the Gherkin jar need to be built as an OSGi bundle.
> (Java) Make the jar a bundle to support execution in OSGi containers.

- README.md
Remove the space in the example #language header on line 128, and tried
to make the descriptive text for the Pickle objects more readable.
> Fixed line 128 syntax error and improved descriptive text for Picke
