cucumber/gherkin

- .github/workflows/test-elixir.yml
Protoc is not needed when building Gherkin
> elixir: Remove redundant Github Action

- CHANGELOG.md
To make releases with polyglot release the changelog has to be compatible with the `changelog` tool. This requires reformatting the entire changelog and unfortunately removing some human flair and details.
> Reformat the CHANGELOG

- php/.php-cs-fixer.php
- php/gherkin-php.razor
- php/src-generated/Parser.php
Closes #35
Adds `src-generated` folder to the coding style check, and fix the razor template so it passes
> PHP: Fix generated code formatting

- .github/workflows/test-php.yml
This writes the github auth token to a config file in ~/.composer, which then uses it when downloading packages
This will help with github rate limiting, as was happening on https://github.com/cucumber/gherkin/pull/52
Documentation here: https://github.com/shivammathur/setup-php#github-composer-authentication
> PHP - Add github auth token to composer configuration

- CHANGELOG.md
- perl/cpanfile
We did not specify a version range for the Cucumber::Messages dependency. This wasn't a problem before, every version of message was usable. However once https://github.com/cucumber/common/pull/1741 was merged this was no longer true.
Fixes #48
I've used an lower and upper bound:
```
requires "Cucumber::Messages", ">= 19.0.0, < 20.0.0";
```
Perl does not appear to have JavaScripts equivalent for any later version within this major (e.g.  `^19.0.0`).
https://metacpan.org/pod/CPAN::Meta::Spec#Version-Ranges
> perl: Use version range for messages

- go/gherkin-generate-tokens/gherkin-generate-tokens.go
- go/go.mod
- go/go.sum
- go/main/main.go
This PR changes Go module name to match source repo.
go mod tidy in a project with the repo as `github.com/cucumber/gherkin/v26` fails with:
```
github.com/cucumber/gherkin/v26: module github.com/cucumber/gherkin@latest found (v26.0.1+incompatible), but does not contain package github.com/cucumber/gherkin/v26
```
----
> fix(go): change module name to match repo

- CHANGELOG.md
- javascript/package.json
- php/composer.json
- ruby/cucumber-gherkin.gemspec
Allow messages v19.1.4 to v20.0.1 to be used by Javascript, PHP and Ruby.
With v19 [the messages protocol was expanded with keyword types][1]. Since then no relevant changes for Gherkin have been made. This means we can expand the range of allowed message versions somewhat.
1: https://github.com/cucumber/messages/blob/main/CHANGELOG.md#1900---2022-05-31
The documentation for the syntax of each can be found here:
- https://semver.npmjs.com/
- https://getcomposer.org/doc/articles/versions.md
- https://guides.rubygems.org/patterns/
Fixes: https://github.com/cucumber/gherkin/issues/82
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-req …
> Allow messages v19.1.4 to v20.0.1 to be used

- java/src/main/java/io/cucumber/gherkin/StringUtils.java
Added description to methods that do non-evident `StringUtils` operations.
Fixes #86 
Nothing.
> Update StringUtils Javadoc

- php/composer.json
- php/phpunit.xml
- php/tests/Parser/RuleTypeTest.php
Replaces #93, migrates the phpunit XML config to the new schema and fixes a broken data provider (they now have to be static methods)
> Fixed: Renovate/phpunit phpunit 10.x

- go/dialects_builtin.go
- go/dialects_builtin.go.jq
Use the standard header for Go generated files, following the spec at https://golang.org/s/generatedcode.
The template go/dialects_builtin.go.jq is fixed and go/dialects_builtin.go is regenerated.
The standard header allows automated tools or IDE to block editing directly generated files. That could help the renovatebot to stop doing invalid changes (see https://github.com/cucumber/gherkin/pull/120#issuecomment-1634352242 and https://github.com/renovatebot/renovate/issues/21010#issuecomment-1634377616).
> go: use standard header in generated file

- .github/workflows/test-python.yml
Removed Python 2.x from CI. Building with Python 2.x fails in CI due to deprecation
https://github.com/cucumber/gherkin/actions/runs/5545057411/jobs/10162291692?pr=134
```
Run actions/setup-python@v4
Installed versions
Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
Version 2.x was not found in the local cache
Error: The version '2.x' with architecture 'x64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Related:
- https://github.com/cucumber/gherkin/issues/125
- https://github.com/cucumber/gherkin/issues/40
> python: Remove Python 2.x from CI

- .github/workflows/test-perl.yml
Since we support older Perls, test with the oldest supported Perl too.
Captures issues before cpantesters will (although it's good to have those as backup).
I hope 1 more matrix variant isn't too much of a burden.
> Test on oldest supported Perl too

- CHANGELOG.md
- perl/cpanfile
- perl/dist.ini
Fixed release procedure:
* The packaging fails on the version range specified for "Cucumber::Messages"
* The CHANGELOG.md didn't actually get packaged
Also updated the Cucumber::Messages minimum version to v22 (in line with Go update).
I'd rather have the release procedure succeed :-)
> Perl add administrativia

- perl/gherkin-perl.razor
- perl/lib/Gherkin/Generated/Parser.pm
- perl/lib/Gherkin/Line.pm
- perl/lib/Gherkin/ParserBase.pm
- perl/lib/Gherkin/ParserContext.pm
- perl/lib/Gherkin/TokenMatcher.pm
The Perl token matcher gained the ability to accept a token and at the same time indicate a token parser error. Before - due to the use of exceptions to indicate parser errors - it would only be possible to achieve one *or* the other.
By making this change, the Perl implementation is able to report the parsing error exactly once, instead of - as it does now - requiring to de-duplicate errors which might be reported multiple times (this can happen due to the fact that the lookahead function of the parser triggers a parser error.
Since the error of the duplicates has already been fixed (the fast way), PR is more of a maintenance type of PR.
During the weekly meeting, we assessed …
> Errors once

- c/src/dialect.c
- dart/assets/gherkin-languages.json
- dotnet/Gherkin/gherkin-languages.json
- elixir/priv/gherkin_languages.json
- gherkin-languages.json
- go/dialects_builtin.go
- javascript/src/gherkin-languages.json
- php/resources/gherkin-languages.json
- python/gherkin/gherkin-languages.json
- ruby/lib/gherkin/gherkin-languages.json
Added a translation of "and" in Italian: "ed".
"Ed" is used when the following word starts with a vowel, to separate the vowel sounds.
Example:
``` gherkin
Dato che ho una pizza
Quando qualcuna mette ananas sulla mia pizza
Ed adoro le mie papille gustative 
Allora non mangio la mia pizza
```
> i18n: Add 'ed' to Italian

- .github/workflows/test-c.yml
- .github/workflows/test-dart.yml
- .github/workflows/test-dotnet.yml
- .github/workflows/test-go.yml
- .github/workflows/test-java.yml
- .github/workflows/test-javascript.yml
- .github/workflows/test-perl.yml
- .github/workflows/test-php.yml
- .github/workflows/test-python.yml
- .github/workflows/test-ruby.yml
Currently, we run ~50 for each commit. This takes up quite a lot of CI resources, resulting in long wait times. Typically, (especially with Renovate) only a single language changes.
> Skip tests for implementations without change

- .github/workflows/release-nuget.yaml
- .github/workflows/test-dotnet.yml
- CHANGELOG.md
- dotnet/Gherkin.Specs/Gherkin.Specs.csproj
- .NET sdk was updated to version 8
- Added .NET 8 to test platforms (new test platforms: .net 6, .net 7, .net 8)
- Use c# lang version 12
.NET 8 soon will be released. This is LTS version and will be good to add it to testing platforms
----
> Added .net 8 to test platforms

- CHANGELOG.md
- c/src/dialect.c
- dart/assets/gherkin-languages.json
- dotnet/Gherkin/gherkin-languages.json
- elixir/priv/gherkin_languages.json
- gherkin-languages.json
- go/dialects_builtin.go
- javascript/src/gherkin-languages.json
- php/resources/gherkin-languages.json
- python/gherkin/gherkin-languages.json
- ruby/lib/gherkin/gherkin-languages.json
Added a translation of "rule" in Dutch: "regel"
Resolves: https://github.com/cucumber/gherkin/issues/105
> i18n: Add 'regel' for 'rule' in Dutch

- CHANGELOG.md
- c/src/dialect.c
- dart/assets/gherkin-languages.json
- dotnet/Gherkin/gherkin-languages.json
- elixir/priv/gherkin_languages.json
- gherkin-languages.json
- go/dialects_builtin.go
- javascript/src/gherkin-languages.json
- php/resources/gherkin-languages.json
- python/gherkin/gherkin-languages.json
- ruby/lib/gherkin/gherkin-languages.json
Added the translation of "rule" in Esperanto: "regulo"
> i18n: Add 'regulo' for 'rule' in Esperanto

- .github/workflows/release-rubygem.yml
- .github/workflows/test-ruby.yml
- CHANGELOG.md
- ruby/Gemfile
- ruby/cucumber-gherkin.gemspec
Bumped minimum messages / ruby ver
----
> [Ruby]: Ruby / Messages bump

- CHANGELOG.md
- ruby/lib/gherkin/query.rb
- ruby/spec/gherkin/query_spec.rb
Introduces a new Gherkin::Query#parent_locations method in the Ruby implementation.
Cucumber::Core::Compiler will use this method to tell Cucumber::Core::Test::Case the locations of its parent lines, such as `Feature:`, `Background:`, and `Rule:`, so that it will correctly match them during location filtering. This particular strategy was identified as potentially reasonable while pairing with @mattwynne.
This is one part of a two-repo PR to resolve the last remaining bits of the regression described in https://github.com/cucumber/cucumber-ruby/issues/1469
- [?] My change requires a change to the documentation.
- [?] Users should know about my change
I'm not sure about these last two, since this could be considered as …
> ruby: introduce Gherkin::Query#parent_locations.

- .github/workflows/release-cpan.yaml
- .github/workflows/release-github.yaml
- .github/workflows/release-mvn.yml
- .github/workflows/release-npm.yml
- .github/workflows/release-nuget.yaml
- .github/workflows/release-php.yaml
- .github/workflows/release-rubygem.yml
- .github/workflows/test-c.yml
- .github/workflows/test-codegen.yml
- .github/workflows/test-dart.yml
- .github/workflows/test-go.yml
- .github/workflows/test-java.yml
- .github/workflows/test-javascript.yml
- .github/workflows/test-perl.yml
- .github/workflows/test-php.yml
- .github/workflows/test-python.yml
- .github/workflows/test-ruby.yml
> Use version 4 of checkout step in workflow

- c/src/ast_builder.c
Passing arguments to 'get_comments' without a prototype is deprecated in all versions of C and is not supported in C2x. Most of the other functions here have correct arguments passed to them except `get_comments`.
Fixing a bug in Cucumber.ml that depends on gherkin-c/libgherkin.so. I get this warning on macOS Sonoma.
```
cc -c -Wall -Werror -g -fPIC  -MMD -MP -MF ../objs/ast_builder.d -I ../include -I . ast_builder.c -o ../objs/ast_builder.o
ast_builder.c:250:92: error: passing arguments to 'get_comments' without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
const GherkinDocument* gherkin_document = GherkinDocument_new(feature, get_comments(ast_builder));
^
ast_builder.c:67:24: error: a function declaration without a …
```
> Fix for get_comments prototype deprecation

- README.md
Updated the Python example for compatibility with the latest API of the package.
Fix Python example so is working and runnable.
See the [compiler.py module](https://github.com/kieran-ryan/gherkin/blob/5ec532537888e41c77dd1dd6ace25a72a44cdf0e/python/gherkin/pickles/compiler.py) for API reference.
Current example, using previous API:
```python
from gherkin.parser import Parser
from gherkin.pickles.compiler import compile
parser = Parser()
gherkin_document = parser.parse("Feature: ...")
pickles = compile(gherkin_document)
```
```console
Traceback (most recent call last):
File "/Users/<user>/projects/python/repository/script.py", line 2, in <module>
from gherkin.pickles.compiler import compile
ImportError: cannot import name 'compile' from 'gherkin.pickles.compiler' …
```
> Update Python example to latest API

- cpp/deps.txt
Pinned messages to v24.0.1.
CI Breaks with 
https://github.com/cucumber/gherkin/actions/runs/7368444336/job/20053098978
```
CMake Error at CMakeLists.txt:13 (find_package):
Could not find a package configuration file provided by "cucumber-messages"
with any of the following names:
cucumber-messagesConfig.cmake
cucumber-messages-config.cmake
Add the installation prefix of "cucumber-messages" to CMAKE_PREFIX_PATH or
set "cucumber-messages_DIR" to a directory containing one of the above
files.  If "cucumber-messages" provides a separate development package or
SDK, be sure it has been installed.
```
Presumably because of https://github.com/cucumber/messages/pull/187
A proper …
> Fix cpp build

- CHANGELOG.md
- c/src/dialect.c
- dart/assets/gherkin-languages.json
- dotnet/Gherkin/gherkin-languages.json
- elixir/priv/gherkin_languages.json
- gherkin-languages.json
- go/dialects_builtin.go
- javascript/src/gherkin-languages.json
- php/resources/gherkin-languages.json
- python/gherkin/gherkin-languages.json
- ruby/lib/gherkin/gherkin-languages.json
> i18n: Add Vietnamese translation of "Rule"

- CHANGELOG.md
- python/.gitignore
- python/MANIFEST
- python/gherkin/token_matcher.py
- python/gherkin/token_matcher_markdown.py
Change Python implementation of markdown token matcher to inherit from feature file token matcher.
- Remove duplicated code - ensuring a source of truth and improved maintainability.
- Add missing entry in manifest for markdown token matcher - added automatically as part of build process when running test suite through `tox`
Existing test suite remained compatible for the feature file and markdown matchers after the change - including with Python 2.
NA.
> Remove duplicate token matcher Python code

- CHANGELOG.md
- ruby/cucumber-gherkin.gemspec
> fix(deps): update dependency cucumber-messages to v24

- README.md
Update Readme for golang to the latest standard. 
After figuring out how to use the latest version of this library for go, I wanted to update the README for anyone in the future who is trying to get it to work. 
----
> update go example in readme

- .github/workflows/test-php.yml
Went from 8.1 to 8.2.
8.1 is EOL.
8.2 is still supported.
When reading https://phpunit.de/announcements/phpunit-11.html I saw that since Feb 2 2024, 8.2 is the oldest still-supported PHP version.
-
> CI: Update latest PHP version to last non-EOL version

- php/composer.json
This version of the php-cs-fixer supports versions of PHP in our matrix.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.51.0
That project's  README states that it supports very new versions.
Our CI error message output was:
```
Run vendor/bin/php-cs-fixer --dry-run --diff fix
vendor/bin/php-cs-fixer --dry-run --diff fix
vendor/bin/psalm --no-cache
vendor/bin/phpunit
shell: /usr/bin/bash -e {0}
env:
COMPOSER_PROCESS_TIMEOUT: 0
COMPOSER_NO_INTERACTION: 1
COMPOSER_NO_AUDIT: 1
COMPOSER_AUTH: {"github-oauth": {"github.com": "***"}}
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.1.*.
Current PHP version: 8.2.15.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code …
```
> [php] Bump required version of the php-cs-fixer

- README.md
Add the uri field which is required by the current implementation of `Compiler`.
----
> Update README.md, python example

- .github/workflows/test-c.yml
- .github/workflows/test-cpp.yml
- .github/workflows/test-dart.yml
- .github/workflows/test-dotnet.yml
- .github/workflows/test-go.yml
- .github/workflows/test-java.yml
- .github/workflows/test-javascript.yml
- .github/workflows/test-perl.yml
- .github/workflows/test-php.yml
- .github/workflows/test-python.yml
- .github/workflows/test-ruby.yml
Build every language on changes to the GitHub workflows. 
We usually only run CI for the languages that changed because it is quite slow. But @olleolleolle was quite confused when CI didn't run for his changes (https://github.com/cucumber/gherkin/pull/233#issuecomment-1991341348). This should prevent that from happening.
> Build every language on changes to the GitHub workflows

- php/composer.json
- php/phpunit.xml
- php/psalm.xml
- php/src/AstNode.php
- php/src/ParserException/UnexpectedEofException.php
- php/src/ParserException/UnexpectedTokenException.php
Psalm's offering news, and our CI had not configured those settings.
This PR fixes a warning that outputs that we should be explicit about this setting.
First, I picked enabling it as the solution. (And, then I continued on that path.)
<details>
<summary>Psalm in CI: found some issues: 9 errors found</summary>
```
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Error: src/AstNode.php:38:37: UnusedParam: Param #1 is never referenced in this method (see https://psalm.dev/135)
Error: src/GherkinParser.php:31:31: UnusedProperty: Cannot find any references to private property Cucumber\Gherkin\GherkinParser::$predictableIds (see https://psalm.dev/150)
Error: src/GherkinParser.php:46:21: PossiblyUnusedMethod: Cannot find any calls to method Cucumber\Gherkin\GherkinParser::parseString (see …
```
> [php] Configure Psalm 6 default settings findUnusedBaselineEntry, findUnusedCode

- php/composer.json
Transitive dependencies do not need to be explicitly declared. Looks like this was originally added to resolve problems caused by using composer update --prefer-lowest that are no longer present.
> php: Remove transitive php-parser dependency

- php/psalm.xml
- php/src/AstNode.php
- php/src/GherkinParser.php
- php/src/Location.php
- php/src/Parser/ParserTrait.php
This PR is an experiment run, to see if Psalm's "find unused" can be tamed, to become useful.
Psalm seems like a cool tool.
Is this a viable path?
I downgraded a Property in a constructor to a regular positional parameter – this was due to a Psalm warning. Is that reasonable?
One error handler dealt with return values, when it looked like that wasn't what it usually did. I turned it into a regular "callbacky" thing, instead.
Well, any thoughts around keeping these Psalm checks enabled would be welcome. Also thoughts around "why this does not suit Gherkin".
> [php] Try to follow Psalm tips

- README.md
- Fixed broken links
- Updated commented language names of samples to headers
- Updated language test statuses to live GitHub workflow badges
- Updated all diagrams to Mermaid
- Several links were broken, including https://ndjson.org which although appeared to be an official link, is now being used for link farming (e.g. links to gambling sites)
- Change commented language names in sample code blocks to headers allows users to link and share to them directly
- Live test status badges is perhaps a more succinct and accurate (live) reflection of language test status
- The AST diagram is now in mermaid. Updated the rest to mermaid for consistency and as it may be easier to update and maintain.
- Is there anything particularly …
> Refresh README elements including broken links

- CHANGELOG.md
- c/src/dialect.c
- cpp/src/lib/gherkin/cucumber/gherkin/dialect.cpp
- dart/assets/gherkin-languages.json
- dotnet/Gherkin/gherkin-languages.json
- elixir/priv/gherkin_languages.json
- gherkin-languages.json
- go/dialects_builtin.go
- javascript/src/gherkin-languages.json
- objective-c/GherkinLanguages/gherkin-languages.json
- php/resources/gherkin-languages.json
- python/gherkin/gherkin-languages.json
- ruby/lib/gherkin/gherkin-languages.json
- Spaces are used at the end of step keywords e.g. `Given ` and have been applied to the Irish translation
- Applied translations that were partially applied across language implementations
- As spaces were missing, and with the language server using the official gherkin parser; steps were incorrectly marked undefined when a step was introduced between the step keyword and the step text; as the space was being considered part of the step text, instead of typically part of the step keyword. This resolves that issue
- Ensure language translations are fully aligned and up to date
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-request …
> Provide trailing space in Irish keywords

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/cmake/cmate
- Added build code to handle failures while downloading tools and/or dependencies
- Fixes #217
> fix(cpp): handle download failures and don't use GitHub api to get latest releases

- go/Makefile
- go/parser.go
- go/parser.go.razor
The go parser is currently generated and then formatted. This however requires that go is installed when generating the parser. This added dependency makes code generation more complicated than it needs to be as this is yet another tool people need to install.
This in turn makes #154 more complicated than it needs to be.
By making the code generator generate formatted code we avoid this problem all together.
> go: generate formatted parser

- CHANGELOG.md
- dotnet/Gherkin.Specs/EventStubs/GherkinEventsProvider.cs
- dotnet/Gherkin/Ast/Background.cs
- dotnet/Gherkin/Ast/Comment.cs
- dotnet/Gherkin/Ast/DocString.cs
- dotnet/Gherkin/Ast/Examples.cs
- dotnet/Gherkin/Ast/Feature.cs
- dotnet/Gherkin/Ast/GherkinDocument.cs
- dotnet/Gherkin/Ast/Location.cs
- dotnet/Gherkin/Ast/Rule.cs
- dotnet/Gherkin/Ast/Scenario.cs
- dotnet/Gherkin/Ast/Step.cs
- dotnet/Gherkin/Ast/StepsContainer.cs
- dotnet/Gherkin/Ast/TableCell.cs
- dotnet/Gherkin/Ast/TableRow.cs
- dotnet/Gherkin/Ast/Tag.cs
- dotnet/Gherkin/AstNode.cs
- dotnet/Gherkin/CucumberMessages/AstMessagesConverter.cs
- dotnet/Gherkin/CucumberMessages/Pickles/PickleCompiler.cs
- dotnet/Gherkin/GherkinDialect.cs
- dotnet/Gherkin/GherkinDialectProvider.cs
- dotnet/Gherkin/GherkinLine.cs
- dotnet/Gherkin/GherkinLineSpan.cs
- dotnet/Gherkin/ParserException.cs
- dotnet/Gherkin/Token.cs
- dotnet/Gherkin/TokenMatcher.cs
- dotnet/Gherkin/TokenScanner.cs
- Adopt c# 12 primary constructors
documentation: https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors
- Remove some unsued private settters
Adopt modern c# language feature to simplify code base
no changes in product. code style changes only
----
> [.NET] Adopt c# 12 primary constructors

- .gitignore
- CHANGELOG.md
- python/gherkin-python.razor
- python/gherkin/__main__.py
- python/gherkin/ast_builder.py
- python/gherkin/ast_node.py
- python/gherkin/dialect.py
- python/gherkin/errors.py
- python/gherkin/gherkin_line.py
- python/gherkin/parser.py
- python/gherkin/parser_types.py
- python/gherkin/pickles/compiler.py
- python/gherkin/stream/gherkin_events.py
- python/gherkin/stream/id_generator.py
- python/gherkin/stream/source_events.py
- python/gherkin/token.py
- python/gherkin/token_formatter_builder.py
- python/gherkin/token_matcher.py
- python/gherkin/token_matcher_markdown.py
- python/gherkin/token_scanner.py
- python/requirements.txt
- python/setup.cfg
- python/setup.py
- python/test/gherkin_in_markdown_token_matcher_test.py
* Added type annotations to the python codebase.
* Added `py.typed` file marker
There are still quite some errors (actual bug, mypy idiosyncrasies, ...) , but at least all the signatures are annotated.
Static type checking make things safer and easier to find usages.
----
> Add type annotations to the python codebase

- c/CMakeLists.txt
CMake below 3.5 is going to be deprecated. Setting the minimum version to 3.5 suppresses that annoying warning. Also, the minimum version should be set before the project, otherwise you also get an annoying warning about that.
Warnings are annoying when they're this simple to fix.
----
> fix: Avoid deprecation warnings in CMakeLists.txt by requiring minimum version 3.5

- .github/workflows/release-pypi.yaml
- .github/workflows/test-python.yml
Replaces `cucumber/action-publish-pypi` with
`pypa/gh-action-pypi-publish@release/v1`. The motivation for using actions in the cucumber org is to ensure that we do not hand release tokens to untrusted code. As the party publishing our python packages, the Python Package Authority can be trusted. Additionally, their action uses trusted publishers which authorizes GitHub with OIDC so no long-lived tokens are used.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
> Python: Replace publish action

- c/CMakeLists.txt
The CONFIGURATION variable is unset, and passing -C without a value breaks with cmake 3.31.0.
Remove an unused `-C` option from `ctest`.
Passing `-C` to `ctest` without a value (as happens because `CONFIGURATION` is unset) is useless before cmake 3.31.0, but breaks beginning with cmake 3.31.0
----
> c: Stop passing -C to ctest

- java/src/main/java/io/cucumber/gherkin/GherkinDialect.java
While the code generation and package private constructor already ensure that all fields are non-null, it is good to have this explicitly enforced in the code.
> java: require all GherkinDialect properties to be non-null

- README.md
Add lacking relation between Rule and Tag in Class Diagram
While developing a Tree-sitter parser for gherkin, I've just realized that the relationship between Rule and Tag is lacking
----
> docs(readme/class-diagram): add lacking rule relation

- .github/workflows/release-nuget.yaml
- .github/workflows/test-codegen.yml
- .github/workflows/test-dotnet.yml
- Pin runner image to `ubuntu-22.04` on .Net and codegen workflows
- Reinstate workflows and enable passing pipelines - as code generation and `.NET` test workflows are incompatible with `ubuntu-24.04` - which is now `ubuntu-latest` (see #349) - and are failing
```bash
$ Run dotnet tool update Berp --version 1.3.0 --tool-path ~/bin
No usable version of libssl was found
```
#349 opened to resolve `ubuntu-24.04` incompatibility.
NA.
> ci: Pin `.Net` and code generation test workflows to `ubuntu-22.04`

- .github/workflows/test-codegen.yml
- Dockerfile
- Bump `berp` from `v1.3.0` -> `v.1.5.0` in [codegen workflow](https://github.com/cucumber/gherkin/blob/e20af1911050d16f1d74df0190c8dedec34c4d10/.github/workflows/test-codegen.yml)
- Bump `berp` from `v1.4.0` -> `v1.5.0` in [parser generator Dockerfile](https://github.com/cucumber/gherkin/blob/e20af1911050d16f1d74df0190c8dedec34c4d10/Dockerfile)
- Bump `.NET` to `v8` from `v5` in code generation workflow and from `v7` in test generation workflow
- Bump `ubuntu-22.04` codegen workflow runner to `ubuntu-latest`
<details>
<summary><a href="https://github.com/gasparnagy/berp">gasparnagy/berp</a></summary>
- Added support for .NET 8.0
- Removed support for .NET 7.0 (end of framework support reached)
- Fix: --version should exit with status 0 (https://github.com/gasparnagy/berp/issues/18)
- …
> chore(deps): update dependency berp to v1.5.0

- CHANGELOG.md
- dotnet/Gherkin.Benchmarks/Gherkin.Benchmarks.csproj
- dotnet/Gherkin.SourceGenerator/Gherkin.SourceGenerator.csproj
Exclude Assemblies from nuget package generation.
The internal Benchmark and SourceGenerator Assemblies shouldn't be published to NuGet, so we should exclude them from NuGet package generation. This fixes a bug when publishing a new release.
----
> [.NET] Exclude Benchmark and SourceGenerator packages from nuget package generation

- .github/workflows/test-dotnet.yml
- CHANGELOG.md
- dotnet/Gherkin.Specs/Gherkin.Specs.csproj
- dotnet/Gherkin/Gherkin.csproj
- Reduce NuGet size by only targeting .NET Standard 2.0
- Only run windows specific test environments (.NET Framework 4.7.2) on windows
- Updated runner to ubuntu-latest
Fixes #349
The .NET tests run on different runtimes (.NET8, .NET9, .NET Framework 4.7.2).
In the github workflow (CI), Ubuntu is used to run the tests.
But Ubuntu/Linux doesn't have a Windows-only .NET Framework 4.7.2 installed.
Instead, Ubuntu used Mono to run the tests. However, as of Ubuntu 24.04, Mono is no longer installed. See https://github.com/actions/runner-images/issues/10636.
This means that even on Ubuntu-22.04 the Gherkin implementation is not tested on the real .NET Framework.
This PR changes that the .NET Framework 4.7.2 runtime is only tested on Windows machines.
On the other hand, we currently have the …
> [.NET] Reduce NuGet size by only targeting .NET Standard 2.0

- .github/workflows/test-ruby.yml
Remove Windows from CI from the ruby test matrix.
In https://github.com/cucumber/gherkin/pull/370 windows was added as an os to run tests on. However, these fail.
> ruby: Remove Windows from CI

- CHANGELOG.md
- c/src/gherkin_line.c
- perl/lib/Gherkin/TokenMatcher.pm
- testdata/bad/backslash_at_end_of_line_in_datatable.feature
- testdata/bad/backslash_at_end_of_line_in_datatable.feature.errors.ndjson
- testdata/bad/file_ends_with_open_docstring.feature
- testdata/bad/file_ends_with_open_docstring.feature.errors.ndjson
- testdata/bad/unexpected_end_of_file.feature
- testdata/bad/unexpected_end_of_file.feature.errors.ndjson
- testdata/bad/unfinished_datatable.feature
- testdata/bad/unfinished_datatable.feature.errors.ndjson
- Added additional error handling edge cases as bad test data
- [c] Optimise error handling for empty datatable rows
- [Perl] Optimise error handling for unclosed DocStrings
These error handling edge cases were reported to the .NET implementation and fixed in an upstream project in 2019. Later, these fixes were also merged into the gherkin repository.
While working on some optimisations (see #344), the question arose whether the regression tests should be ported to the gherkin repository. This ensures that all implementations can handle these edge cases that have been reported by users.
The Perl implementation in general (first time …
> Additional error handling edge cases

- CHANGELOG.md
- java/src/main/java/io/cucumber/gherkin/GherkinDialect.java
- java/src/main/java/io/cucumber/gherkin/GherkinDialectProvider.java
- java/src/main/java/io/cucumber/gherkin/TokenMatcher.java
- java/src/test/java/io/cucumber/gherkin/GherkinDialectProviderTest.java
- java/src/test/java/io/cucumber/gherkin/GherkinDialectTest.java
Separating out the elements from https://github.com/cucumber/gherkin/pull/372 that involve the GherkinDialect
* Optimize memory size of `stepKeywords`
* Use `EnumSet` for `stepKeywordsTypes`
* Adds `getDistinctStepKeywordTypes` that returns the `EnumSet`
* Deprecates `getStepKeywordTypes`
> Optimize GherkinDialect performance

- CHANGELOG.md
- java/src/main/java/io/cucumber/gherkin/EncodingParser.java
- java/src/test/java/io/cucumber/gherkin/EncodingParserTest.java
Separating out the elements from https://github.com/cucumber/gherkin/pull/372 that involve the GherkinDialect
* Optimize `EncodingParser`
> java: Optimize EncodingParser

- java/src/main/java/io/cucumber/gherkin/Locations.java
- java/src/test/java/io/cucumber/gherkin/LocationsTest.java
Added unit tests for `Locations`.
Ensure that the new `Locations.getLong()` method works properly (behavior, thread-safety and performance).
TLDR: the current version is the fastest one.
I made a micro-benchmark for different variants and it appears that this one is the fastest for feature files up to 4000 lines. When the feature file contains more than 4000 lines, performance is a bit slower than the original `Long.valueOf`. But this is a very long feature file and probably against the good BDD practices. According to ChatGPT, the typical feature file is up to 50 lines and max 300 lines (I didn't verify).
I tested several variants:
- static preinitialized cache of 127 elements …
> Added unit tests for Locations

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/lib/gherkin/CMakeLists.txt
PR https://github.com/cucumber/gherkin/pull/328 did not end up using the `VERSION` file for C++ project versioning or for C++ shared-library versioning or ABI/`SONAME` versioning, even though I think that’s what was desired, c.f. https://github.com/cucumber/gherkin/pull/328#issuecomment-2508925487.
This PR imitates the version/`SOVERSION` handling that was added to the C library in the C++ library.
Fixes #375
(This is breaking only in that it affects the version number and `SONAME` version / ABI version of the C++ library. It does not affect the API.)
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encoura …
> fix(cpp): Actually use the VERSION file

- CHANGELOG.md
- java/src/main/java/io/cucumber/gherkin/GherkinDialect.java
Step keywords may be prefixes of each other. For example in French several variations of given start with `Etant donné`. When this is the case Gherkin should prefer the longest possible keyword.
This is currently only implicitly enforced by manually ordering the keywords.
However, for Creole language the prefixes are spread between then and when so manually sorting them is no longer possible.
Partially resolves: #400
> java: Prefer the longest step keyword

- CHANGELOG.md
- php/.gitignore
- php/src/GherkinDialect.php
- php/tests/GherkinDialectTest.php
Step keywords may be prefixes of each other. For example in French several variations of given start with `Etant donné`. When this is the case Gherkin should prefer the longest possible keyword.
This is currently only implicitly enforced by manually ordering the keywords.
However, for Creole language the prefixes are spread between then and when so manually sorting them is no longer possible.
This is the PHP implementation of the fix for #400.
> [PHP] Prefer the longest step keyword

- c/src/token_matcher.c
Sets the matched keyword type to `Keyword_Action` or `Keyword_Outcome`, rather than to `Keyword_Unknown`, when matching keywords of the respective types.
When this PR is combined with https://github.com/cucumber/gherkin/pull/417, the C acceptance tests (`make acceptance`) pass. Together, these two PR’s constitute a partial fix for https://github.com/cucumber/gherkin/issues/412.
I was surprised I did not have to change `Keyword_Unknown` to `Keyword_Conjunction` for the and/but case, which seems to parallel the action and outcome cases. If I do change the and/but case, the acceptance tests fail.
https://github.com/cucumber/gherkin/blob/768a54048dce8edb87205ff719f313622551c800/c/src/token_matcher.c#L151-L158
I would love to …
> [c] Fix setting keyword type when matching Action or Outcome

- CHANGELOG.md
- java/src/main/java/io/cucumber/gherkin/StringUtils.java
- java/src/test/java/io/cucumber/gherkin/GherkinLineTest.java
- java/src/test/java/io/cucumber/gherkin/StringUtilsTest.java
Define whitespace as Unicode category `Zs` or its bidirectional class `WS`, `B`, or `S`.
Gherkin lines were trimmed according regex pattern `\s` + NEL + NBSP while comments on tags lines were assumed to be delimited by just `\s#`. This leads to some inconsistent behaviour where adding a comment to the end of a tag line can make the tag line invalid.
Each Gherkin implementations uses different definitions of whitespace.
These can be roughly categorized as using Unicode:
* C uses a hardcoded set from Wikipedia Whitespace character Unicode table[1]
* .Net uses Unicode category `Zs`, `Zl` and `Zp` and `\t`, `\v`, `\f`, `\r` and NEL[3].
* Javascript uses the regex pattern `\s` which match the set used by C + BOM[4]
* Python uses Unicode category `Zs` or its bidirectional class `WS`, `B`, or …
> java: Use a more consistent definition of whitespace

- .github/workflows/release-pypi.yaml
Introduced on #439 merge conflict resolution from #451 changes to bump the checkout action while the other dropped the action ‘name’ and ‘uses’ the action directly, so the merged change as before had no dash and caused a syntax error.
- Fixes the Python release workflow
NA
> fix: missing dash Python release workflow

- dotnet/Gherkin/Gherkin.csproj
This reverts commit 9da43f05322ce8f512554c3ebdf5d37b0e6c8c29.
Merged with too little discussion.
In #426 I specifically asked for a range, because the messages project churns through majors quite quickly. Most of these don't impact Gherkin. With a version range we can release messages without also having to make major releases for Gherkin.
> Revert "Dotnet. Remove version pinning (#455)"

- CONTRIBUTING.md
Updated berp and .NET versions in non-docker contributing guidelines to the latest
Berp v1.4.0 is incompatible with .NET v8 https://github.com/gasparnagy/berp/releases/tag/v1.5.0 and will not work for contributors that are not using the Dockerfile - where the correct versions are specified.
- NA
> docs: Correct .NET and berp versions in contributing guidelines

- java/src/main/java/io/cucumber/gherkin/StringUtils.java
- java/src/main/java/io/cucumber/gherkin/TableRowLine.java
- java/src/main/java/io/cucumber/gherkin/TagLine.java
- java/src/test/java/io/cucumber/gherkin/StringUtilsTest.java
- java/src/test/java/io/cucumber/gherkin/TagLineTest.java
Some unnecessary operations have been removed:
- `StringUtils.trimAndIndentKeepNewLines(..)` now receive a `StringBuilder` instead of a `String`
- `StringUtils.trimAndIndentKeepNewLines(..)` and `StringUtils.trimAndIndent(..)` now computes the indentation without using codepoints (because all whitespace characters have only 1 character). 
- `TagLine.parse(..)` now computes the codepoints count incrementally (avoids recomputing the codepoint count from the beginning of the string when there are more that one tag on the line).
Although I didn't benchmark the changes, not doing unnecessary things should be faster.
I don't think these minor refactoring requires to update the CHANGELOG.md (the …
> feat: avoid unnecessary String instantiation and codePointCount
