cucumber/gherkin

javascript/lib/gherkin/errors.js
useful when plugging into an ace editor worker
=> add all errors to js CompositeParserException so it can be inspected later

.travis.yml, Makefile, golang/.gitignore, golang/Makefile, golang/gherkin-golang.razor, golang/src/gherkin-generate-ast/gherkin-generate-ast.go, golang/src/gherkin-generate-tokens/gherkin-generate-tokens.go, golang/src/github.com/cucumber/gherkin3/ast/ast.go, golang/src/github.com/cucumber/gherkin3/astbuilder.go, golang/src/github.com/cucumber/gherkin3/dialect.go, golang/src/github.com/cucumber/gherkin3/dialects_builtin.go, golang/src/github.com/cucumber/gherkin3/example_test.go, golang/src/github.com/cucumber/gherkin3/gherkin3.go, golang/src/github.com/cucumber/gherkin3/matcher.go, golang/src/github.com/cucumber/gherkin3/parser.go
first working version passing all the acceptance tests.
still need to cleanup a lot of stuff, but I think this code is ready for others to take it for a spin :rocket: 
btw, amazing how fast it already processes all the acceptance tests:
``` bash
$ cd golang; time make test -B >/dev/null
real	0m0.329s
user	0m0.160s
sys	0m0.166s
```
=> new Parser: golang

.travis.yml, golang/Makefile
please wait until merge for the Pull-Request build to complete
=> try to fix travis-ci golang build

Makefile
A more generalized version of the global `Makefile`.
I prefer pattern rules over explicit ones, but some do not. What do you think?
=> Generic makefile

dotnet/Gherkin/AstBuilder.cs, dotnet/Gherkin/Parser.cs, gherkin.berp, go/astbuilder.go, go/parser.go, java/src/main/java/gherkin/AstBuilder.java, java/src/main/java/gherkin/Parser.java, javascript/lib/gherkin/ast_builder.js, javascript/lib/gherkin/parser.js, ruby/lib/gherkin/ast_builder.rb, ruby/lib/gherkin/parser.rb
This is a small change in the grammar, that i needed for better editor support. Now I reapplied it to all languages (i hope).
=> Examples definition in grammar

dotnet/Gherkin/ParserException.cs, go/parser.go, go/parser.go.razor, java/src/main/java/gherkin/ParserException.java, javascript/lib/gherkin/errors.js, ruby/lib/gherkin/errors.rb, testdata/bad/multiple_parser_errors.feature.errors, testdata/bad/single_parser_error.feature.errors
This is a small improvement (provide column for unexpected token error).
=> Improve error location

go/matcher.go
since we can get the amount of trimmed text by comparing string lengths.
@muhqu please take a look
=> Use string functions for left trimming

.travis.yml, dotnet/Gherkin/Ast/Examples.cs, go/ast.go, go/astbuilder.go, java/src/main/java/gherkin/AstBuilder.java, java/src/main/java/gherkin/ast/Examples.java, java/src/main/java/gherkin/compiler/Compiler.java, javascript/lib/gherkin/ast_builder.js, ruby/lib/gherkin/ast_builder.rb, testdata/good/descriptions.feature.ast.json, testdata/good/example_tokens_everywhere.feature.ast.json, testdata/good/scenario_outline.feature.ast.json, testdata/good/several_examples.feature.ast.json, testdata/good/tags.feature.ast.json
As discussed at commit https://github.com/cucumber/gherkin3/commit/e89c30e2ea612d5ac89e93b830c1df3c6a644b95 we switch back to separated Header/Body for examples.
I have created the expected AST files and the .NET code, but have no time now for the other languages, so if anyone want to pick it -> go ahead.
=> Header and body in examples (WIP)

gherkin-languages.json
Adding Irish language in the right project this time!
=> Adding Irish language (ga)

README.md, ruby/README.md
=> Improve documentation

README.md
Found a couple of markdown mistakes that made a sentence somewhat difficult to understand. Quick fix.
=> correct some markdown in the README

python/gherkin3/ast_builder.py
The existing code was correct, but redundant.
Code shortened and comment removed.
=> (Python) Fix “translated from JS” bool evaluation

python/Makefile, python/bin/gherkin-generate-pickles, python/gherkin3/pickles/compiler.py, python/test/pickles_test/compiler_test.py
This is a compiler adapted from other implementations (mostly JS, some Java).  
It includes a pathetic test (adapted from Java), and an executable in `bin/`.  
Needs more tests (for sure!)—but it works!
=> (Python) Add compiler

CONTRIBUTING.md
Add some onboarding information.
=> Enrich CONTRIBUTING.md

python/setup.py
=> Fix #156: Add `gherkin.pickles` package to setup.py

javascript/index.js, javascript/lib/gherkin/dialects.js, javascript/lib/gherkin/token_matcher.js
=> javascript: expose dialects

README.md
=> readme - fix link to gherkin2

README.md
Since **godog** is using this library as a gherkin3 parser, thought it would be useful to share
=> link a project which implements this library

dotnet/Gherkin/gherkin-languages.json, gherkin-languages.json, go/dialects_builtin.go, java/src/main/resources/gherkin/gherkin-languages.json, javascript/lib/gherkin/gherkin-languages.json, objective-c/GherkinLanguages/gherkin-languages.json, python/gherkin/gherkin-languages.json, ruby/lib/gherkin/gherkin-languages.json
Asturian is a romance language spoken in North Western Spain.
https://www.ethnologue.com/language/ast
I would like to add it to **gherkin**, so we can use asturian to write our test and define our programs.
[ast]
L'Asturianu ye una llingua romace que fálase nel Noroeste d'España.
https://www.ethnologue.com/language/ast
Prestaríame amestalo a **gherkin**, pa poder usar l'asturianu pa escribir nuestres pruebes y especificaciones de nuestros programes.
=> Added asturian language

gherkin-languages.json
If you have any questions please let me know.
=> Added Macedonian language to the json
